ladybug-tools/dragonfly-energy

.travis.yml, README.md, docs/README.md, dragonfly_energy/__init__.py, dragonfly_energy/_extend_dragonfly.py, dragonfly_energy/properties/__init__.py, dragonfly_energy/properties/building.py, dragonfly_energy/properties/room2d.py, dragonfly_energy/properties/story.py, requirements.txt, tests/building_extend_test.py, tests/conftest.py, tests/example_test.py, tests/room2d_extend_test.py, tests/story_extend_test.py
This commit adds all of the energy properties for the dragonfly-core objects along with the code to extend dragonfly-core.
@mostaphaRoudsari ,
The tests are all complete for this PR but they will not pass until we merge this PR in over on dragonfly-core:
https://github.com/ladybug-tools/dragonfly-core/pull/9
=> feat(objects): Add objects for EnergyProperties

dragonfly_energy/_extend_dragonfly.py, dragonfly_energy/properties/building.py, dragonfly_energy/properties/context.py, dragonfly_energy/properties/model.py, dragonfly_energy/properties/room2d.py, dragonfly_energy/properties/story.py, tests/building_extend_test.py, tests/context_extend_test.py, tests/model_extend_test.py, tests/room2d_extend_test.py, tests/story_extend_test.py
This PR is meant to be coordinated with [this one over on dragonfly-core](https://github.com/ladybug-tools/dragonfly-core/pull/17) and extends the new objects with energy properties.  The tests won't pass on this PR until we merge in that dragonfly-core PR but I'd like to coordinate the merging of these two together to avoid messing up SOM's testing.
I am still finishing up some of the tests but all of the code for the libraries in this PR is finished and ready for review, @mostaphaRoudsari .
=> feat(model): Add EnergyProperties for Model and ContextShade

dragonfly_energy/properties/building.py, dragonfly_energy/properties/model.py, dragonfly_energy/properties/room2d.py, dragonfly_energy/properties/story.py, tests/building_extend_test.py, tests/model_extend_test.py, tests/room2d_extend_test.py, tests/story_extend_test.py
This commit brings the tests in line with [this PR](https://github.com/ladybug-tools/honeybee-energy/pull/69) on honeybee_energy.
=> feat(hvac): Upgrade to work with honeybee_energy refactor

tests/building_extend_test.py, tests/context_extend_test.py, tests/room2d_extend_test.py, tests/story_extend_test.py
This code will eventually be taken out of this repo and put into the [dragonfly-schema repo](https://github.com/ladybug-tools/dragonfly-schema). But I'm just updating it here until the dragonfly-schema repo is all set up.
=> docs(tests): Update sample-generating code

tests/building_extend_test.py, tests/context_extend_test.py, tests/model_extend_test.py, tests/room2d_extend_test.py, tests/story_extend_test.py
This commit brings this repo up-to-date with [this PR](https://github.com/ladybug-tools/dragonfly-core/pull/24).
=> tests(room2d): Update tests based on change in dragonfly_core

docs/_static/custom.css, docs/_templates/layout.html, docs/conf.py, dragonfly_energy/properties/building.py, dragonfly_energy/properties/context.py, dragonfly_energy/properties/model.py, dragonfly_energy/properties/room2d.py, dragonfly_energy/properties/story.py
Hi @chriswmackey. I had no problems with this library. Please feel free to take a look whenever you have a chance.
=> Format docstrings for correct display in sphinx-generated bootstrap pages

.dependabot/config.yml
FYI, Mostapha, this should fix the previous issue we saw.
=> ci(dependabot): Fix automerge settings

dragonfly_energy/cli/translate.py
Resolves https://github.com/ladybug-tools/dragonfly-energy/issues/74
=> feat(cli): Improve CLI logs

dragonfly_energy/cli/simulate.py
This will give Konrad the means of adding the reporting measures into the CLI run.
=> fix(cli): Update simulate command to include base_osw

dragonfly_energy/cli/simulate.py, dragonfly_energy/run.py, requirements.txt
I also fixed a small bug in the output of html files in the run module.
=> fix(cli): Update method in cli.simulate group

dragonfly_energy/properties/building.py, dragonfly_energy/properties/room2d.py, dragonfly_energy/properties/story.py, requirements.txt
This commit adds support for the assignment of a single ideal air system to multiple dragonfly Room2Ds.
=> fix(hvac): Update HVAC to align with the new honeybee-energy

dragonfly_energy/config.json, dragonfly_energy/config.py, dragonfly_energy/run.py
This commit adds two new variables to the config to sense the URBANopt CLI installation and the executable file that sets the environment variables.
I have tested it on Windows and all is working well.  The changes here should enable it to work on MAc but I will test soon.
=> feat(urbanopt): Update config and run to handle the new URBANopt setup

dragonfly_energy/cli/simulate.py, dragonfly_energy/cli/translate.py, tests/cli_translate_test.py
This commit includes several fixes to the CLI commands that ensure the help docs display correctly and that simulations are run with similar conventions to honeybee-energy.
=> style(cli): Improve CLI commands

dragonfly_energy/cli/simulate.py
Resolves https://github.com/ladybug-tools/dragonfly-energy/issues/478
=> fix(cli): Add missing import statement

.github/workflows/ci.yaml, Dockerfile, dragonfly_energy/properties/building.py, tests/building_extend_test.py
I am also updating the CI and adding a Dockerfile so that we get a dragonfly-energy docker image with each release.
=> fix(building): Add a method to diversify programs

MANIFEST.in, dragonfly_energy/opendss/__init__.py, dragonfly_energy/opendss/_base.py, dragonfly_energy/opendss/connector.py, dragonfly_energy/opendss/lib/__init__.py, dragonfly_energy/opendss/lib/electrical_database.json, dragonfly_energy/opendss/lib/transformers.py, dragonfly_energy/opendss/substation.py, dragonfly_energy/opendss/transformer.py, dragonfly_energy/opendss/transformerprop.py, dragonfly_energy/opendss/wire.py
This isn't complete yet but I want to merge it in as I'll be making other breaking changes now.
=> style(opendss): Add a sub-package to handle OpenDSS geometry

dragonfly_energy/run.py, dragonfly_energy/writer.py
This is going to make things a lot easier for users.
=> feat(run): Auto-assign the CPU count based on the machine

dragonfly_energy/writer.py
This should make the simulation a bit faster and also avoid certain failure scenarios.
=> fix(writer): Avoid removing the .bundle with every run

dragonfly_energy/run.py, dragonfly_energy/writer.py
More info is here:
https://discourse.ladybug.tools/t/geojson-to-urbanopt-changes-the-model-index/17363/6
=> fix(run): Have run urbanopt return result files in geojson order

dragonfly_energy/run.py, dragonfly_energy/writer.py
This is going to help so much with debugging people's issues.
=> fix(run): Report the URBANopt stderr whenever the simulation fails

dragonfly_energy/cli/translate.py
Rename from to-gbxml to to-sdd
=> fix(translate): use the correct name for the cli command

dragonfly_energy/cli/translate.py
This helps the roof calculation get resolved in a way that works better with destination engines.
=> fix(translate): Perform gbXML translation with E+ native tolerance

dragonfly_energy/properties/model.py, tests/model_extend_test.py
This commit also introduces a new way to resolve the conflicting constructions that can happen when two adjacent rooms are given different construction sets. This avoids the need to add a validation error for mismatched interior adjacent constructions.
=> feat(model): Refactor validation to be much more robust
